<?php

use Illuminate\Database\Seeder;

class ConsigneeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('consignees')->insert([
            [
                'name'                  => 'Zara',
                'logo'                  => 'zara.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Bershka',
                'logo'                  => 'bershka.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'H&M',
                'logo'                  => 'hm.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'M&S',
                'logo'                  => 'ms.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Pull & Bear',
                'logo'                  => 'pb.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Stradivarius',
                'logo'                  => 'stradivarius.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'F&F',
                'logo'                  => 'ff.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'LPP',
                'logo'                  => 'lpp.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'OYSHO',
                'logo'                  => 'oysho.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Mossimo Dutti',
                'logo'                  => 'mossimodutti.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Decathlon',
                'logo'                  => 'decathlon.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'UNIQLO',
                'logo'                  => 'uniqlo.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Levis',
                'logo'                  => 'levis.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'C&A',
                'logo'                  => 'ca.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Lefties',
                'logo'                  => 'lefties.png',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Target',
                'logo'                  => 'target.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'name'                  => 'Tesco',
                'logo'                  => 'tesco.jpg',
                'phone'                 => '+90 850 441 6789',
                'address'               => 'Fatih Mahallesi, 1198 Sokak No: 1/A Sarnıç, Gaziemir İzmir / TÜRKİYE',
                'auth_name'             => 'Mehmet Karabulut',
                'auth_phone'            => '+90 850 441 6789',
                'status'                => 1,
                'created_user_id'       => 1,
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ]
        ]);
    }
}
