<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            [
                'title'         => 'Profil Bilgileri Görüntüleme',
                'method'        => 'GET,HEAD',
                'controller'    => 'ProfileController',
                'action'        => 'show',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Profil Bilgileri Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'ProfileController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Ayar Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'SettingsController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Ayar Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'SettingsController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Ayar Ekleme',
                'method'        => 'POST',
                'controller'    => 'SettingsController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Ayar Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'SettingsController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Ayar Silme',
                'method'        => 'DELETE',
                'controller'    => 'SettingsController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'PermissionController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'PermissionController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Ekleme',
                'method'        => 'POST',
                'controller'    => 'PermissionController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'PermissionController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'PermissionController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'İzin Silme',
                'method'        => 'DELETE',
                'controller'    => 'PermissionController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'RoleController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'RoleController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Ekleme',
                'method'        => 'POST',
                'controller'    => 'RoleController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'RoleController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'RoleController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Rol Silme',
                'method'        => 'DELETE',
                'controller'    => 'RoleController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'MenuController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'MenuController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Ekleme',
                'method'        => 'POST',
                'controller'    => 'MenuController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'MenuController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'MenuController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Menü Silme',
                'method'        => 'DELETE',
                'controller'    => 'MenuController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'UserController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'UserController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Ekleme',
                'method'        => 'POST',
                'controller'    => 'UserController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'UserController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'UserController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Kullanıcı Silme',
                'method'        => 'DELETE',
                'controller'    => 'UserController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'TranslationController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'TranslationController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Ekleme',
                'method'        => 'POST',
                'controller'    => 'TranslationController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'TranslationController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'TranslationController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Çeviri Silme',
                'method'        => 'DELETE',
                'controller'    => 'TranslationController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Ekleme',
                'method'        => 'POST',
                'controller'    => 'CompanyController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Detay Sayfası',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyController',
                'action'        => 'show',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'CompanyController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Silme',
                'method'        => 'DELETE',
                'controller'    => 'CompanyController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Ekleme',
                'method'        => 'POST',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Detay Sayfası',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'show',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Firma Cihaz Silme',
                'method'        => 'DELETE',
                'controller'    => 'CompanyDeviceController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'OrderController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'OrderController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Ekleme',
                'method'        => 'POST',
                'controller'    => 'OrderController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Detay Sayfası',
                'method'        => 'GET,HEAD',
                'controller'    => 'OrderController',
                'action'        => 'show',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'OrderController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'OrderController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sipariş Silme',
                'method'        => 'DELETE',
                'controller'    => 'OrderController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsignmentController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsignmentController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Ekleme',
                'method'        => 'POST',
                'controller'    => 'ConsignmentController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Detay Sayfası',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsignmentController',
                'action'        => 'show',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsignmentController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'ConsignmentController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Silme',
                'method'        => 'DELETE',
                'controller'    => 'ConsignmentController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevkiyat Durum Değiştirme',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsignmentController',
                'action'        => 'status',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Listesi',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsigneeController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Ekleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsigneeController',
                'action'        => 'create',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Ekleme',
                'method'        => 'POST',
                'controller'    => 'ConsigneeController',
                'action'        => 'store',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Düzenleme Formu',
                'method'        => 'GET,HEAD',
                'controller'    => 'ConsigneeController',
                'action'        => 'edit',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Düzenleme',
                'method'        => 'PUT,PATCH',
                'controller'    => 'ConsigneeController',
                'action'        => 'update',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Sevk Edilecek Firma Silme',
                'method'        => 'DELETE',
                'controller'    => 'ConsigneeController',
                'action'        => 'destroy',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],





            [
                'title'         => 'Raporlar',
                'method'        => 'GET,HEAD',
                'controller'    => 'ReportsController',
                'action'        => 'index',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'title'         => 'Paket Raporu İndirme',
                'method'        => 'GET',
                'controller'    => 'ReportsController',
                'action'        => 'exportPackagePdf',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s')
            ],
            [
                'title'         => 'Model Raporu İndirme',
                'method'        => 'GET',
                'controller'    => 'ReportsController',
                'action'        => 'exportModelPdf',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s')
            ],
            [
                'title'         => 'Epc Raporu İndirme',
                'method'        => 'GET',
                'controller'    => 'ReportsController',
                'action'        => 'exportEpcPdf',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s')
            ],
            [
                'title'         => 'Silinmiş Paket Raporu İndirme',
                'method'        => 'GET',
                'controller'    => 'ReportsController',
                'action'        => 'exportDeletedPackagePdf',
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s')
            ]
        ]);
    }
}
